[package]
name = "shortcircuit"
version = "0.1.0"
authors = ["amfl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tui = "0.9.5"
termion = "1.5.5"
rand = "0.7.3"
serde_json = "1.0"
